/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, int operando_derecha, char operador, int operando_izquierda)
{
	CLIENT *clnt;
	int  *resultado;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCULADORA, CALCULADORA1, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	switch(operador) {
		case '+': resultado = sumar_1(operando_derecha, operando_izquierda, clnt); break;
		case '-': resultado = restar_1(operando_derecha, operando_izquierda, clnt); break;
		case 'x': resultado = multp_1(operando_derecha, operando_izquierda, clnt); break;
		case '/': resultado = divid_1(operando_derecha, operando_izquierda, clnt); break;
		case '^': resultado = power_1(operando_derecha, operando_izquierda, clnt); break;
		case '%': resultado = modulo_1(operando_derecha, operando_izquierda, clnt); break;
		default: printf("Operador no válido\n. Válidos: +, -, *, /"); exit(1); break;
	}

	if (resultado == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	/* Resultado */
	printf("%i %c %i = %d", operando_derecha, operador, operando_izquierda, *resultado);

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc != 5) {
		printf ("Parámetros erróneos: ./<programa> <maquina> <entero> <operador> <entero>\n");
		exit (1);
	}

	host = argv[1];
	calculadora_1 (host, atoi(argv[2]), *argv[3], atoi(argv[4]));
	exit (0);
}
