/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>

t_vector *
suma_2_svc(t_vector a, t_vector b,  struct svc_req *rqstp)
{
	static t_vector  result;
	result.t_vector_len = a.t_vector_len;
	result.t_vector_val = malloc(a.t_vector_len*sizeof(float));
	
	for(int i = 0; i < result.t_vector_len; i++){
		result.t_vector_val[i] = a.t_vector_val[i] + b.t_vector_val[i];
		printf("%lf ", result.t_vector_val[i]);
	}

	return &result;
}

int *
sumar_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a + b;

	return &result;
}

int *
restar_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a - b;

	return &result;
}

int *
multp_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a * b;

	return &result;
}

int *
divid_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a / b;

	return &result;
}

int *
power_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = pow(a, b);

	return &result;
}

int *
modulo_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = fmod(a, b);

	return &result;
}