/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>

t_vector *
suma_2_svc(t_vector a, t_vector b,  struct svc_req *rqstp)
{
	static t_vector  result;
	result.t_vector_len = a.t_vector_len;
	result.t_vector_val = malloc(a.t_vector_len*sizeof(float));
	
	for(int i = 0; i < result.t_vector_len; i++){
		result.t_vector_val[i] = a.t_vector_val[i] + b.t_vector_val[i];
	}

	return &result;
}

t_vector *
resta_2_svc(t_vector a, t_vector b,  struct svc_req *rqstp)
{
	static t_vector  result;
	result.t_vector_len = a.t_vector_len;
	result.t_vector_val = malloc(a.t_vector_len*sizeof(float));
	
	for(int i = 0; i < result.t_vector_len; i++){
		result.t_vector_val[i] = a.t_vector_val[i] - b.t_vector_val[i];
	}

	return &result;
}

t_vector *
multp_2_svc(t_vector a, t_vector b,  struct svc_req *rqstp)
{
	static t_vector  result;
	result.t_vector_len = a.t_vector_len;
	result.t_vector_val = malloc(a.t_vector_len*sizeof(float));
	
	for(int i = 0; i < result.t_vector_len; i++){
		result.t_vector_val[i] = a.t_vector_val[i] * b.t_vector_val[i];
	}

	return &result;
}

t_vector *
prodv_2_svc(t_vector a, t_vector b,  struct svc_req *rqstp)
{
	static t_vector  result;
	result.t_vector_len = 3;
	result.t_vector_val = malloc(3*sizeof(float));
	
	result.t_vector_val[0] = (a.t_vector_val[1]*b.t_vector_val[2])-(a.t_vector_val[2]*b.t_vector_val[1]);
	result.t_vector_val[1] = (a.t_vector_val[2]*b.t_vector_val[0])-(a.t_vector_val[0]*b.t_vector_val[2]);
	result.t_vector_val[2] = (a.t_vector_val[0]*b.t_vector_val[1])-(a.t_vector_val[1]*b.t_vector_val[0]);

	return &result;
}

int *
sumar_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a + b;

	return &result;
}

int *
restar_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a - b;

	return &result;
}

int *
multp_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a * b;

	return &result;
}

int *
divid_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a / b;

	return &result;
}

int *
power_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = pow(a, b);

	return &result;
}

int *
modulo_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = fmod(a, b);

	return &result;
}