/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_2_argument (XDR *xdrs, suma_2_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_2_argument (XDR *xdrs, resta_2_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multp_2_argument (XDR *xdrs, multp_2_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_prodv_2_argument (XDR *xdrs, prodv_2_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multp_1_argument (XDR *xdrs, multp_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_divid_1_argument (XDR *xdrs, divid_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_power_1_argument (XDR *xdrs, power_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modulo_1_argument (XDR *xdrs, modulo_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
