/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
sumar_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a + b;

	return &result;
}

int *
restar_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a - b;

	return &result;
}

int *
multp_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a * b;

	return &result;
}

int *
divid_1_svc(int a, int b,  struct svc_req *rqstp)
{
	static int  result;

	result = a / b;

	return &result;
}
